### ISSUE TITLE
Bump botan to v1.11

### ISSUE THREAD

**Issue by yuvadm** [mempko/firestr#14]
Why no support for botan 1.11? Is there any major holdback from supporting it?

At least on Arch it would be easier to support with an official package, rather than a 1.10 AUR package. Also might be relevant for the new Debian release, and possibly for new versions of Ubuntu as well.

**Comment by mempko** [comment]
Have you tried using botan 1.11 instead? The reason I am using 1.10 is because that is what is available on ubuntu 14.04. When I migrate to 15.04 for the default debian build I will upgrade. 

I might work out of the box, but I haven't tested.

**Comment by snassar** [comment]
Building against botan 1.11 gives the following:
```
[ 51%] Built target fire_conversation
/home/snassar/forge/firestr/src/security/security.cpp:43:27: fatal error: botan/look_pk.h: No such file or directory
 #include <botan/look_pk.h>
                           ^
compilation terminated.
src/security/CMakeFiles/fire_security.dir/build.make:77: recipe for target 'src/security/CMakeFiles/fire_security.dir/security.cpp.o' failed
make[2]: *** [src/security/CMakeFiles/fire_security.dir/security.cpp.o] Error 1
CMakeFiles/Makefile2:223: recipe for target 'src/security/CMakeFiles/fire_security.dir/all' failed
make[1]: *** [src/security/CMakeFiles/fire_security.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 98%] Built target fire_gui
Makefile:136: recipe for target 'all' failed
make: *** [all] Error 2
```
I tried to remove

```
#include <botan/look_pk.h>
```
but that didn't work.

**Comment by mempko** [comment]
ubuntu 15.04 seems to still ship 1.10 :-( 

I am debating in my head if I want to go with static linking but it would make creating a src deb that much harder.

**Comment by yuvadm** [comment]
:-1: for static linking, harder for all packagers.

**Comment by mempko** [comment]
@yuvadm You are right. Silly silly idea. Of course another option is to switch to a different library too.

I will table this for now until more systems support 1.11 out of the box. I'll tag it to revisit later.
